#!/usr/bin/env bun
import fs from 'node:fs';
import path from 'node:path';

const PUBLIC_DIR = path.join(process.cwd(), 'public');
const SHELL_DIR = path.join(process.cwd(), 'shell');
const OUTPUT_FILE = path.join(process.cwd(), 'src', 'assets', 'generated.mjs');
const ASSETS_DIR = path.join(process.cwd(), 'src', 'assets');

const COMPRESS_ASSETS = process.env.COMPRESS_ASSETS === 'true';

function getContentType(filePath) {
  const ext = path.extname(filePath);
  const types = {
    '.html': 'text/html',
    '.css': 'text/css',
    '.js': 'application/javascript',
    '.mjs': 'application/javascript',
    '.json': 'application/json',
    '.svg': 'image/svg+xml',
    '.png': 'image/png',
    '.jpg': 'image/jpeg',
    '.jpeg': 'image/jpeg',
    '.gif': 'image/gif',
    '.woff2': 'font/woff2',
    '.woff': 'font/woff',
    '.ttf': 'font/ttf',
  };
  return types[ext] || 'application/octet-stream';
}

function isBinaryFile(filePath) {
  const ext = path.extname(filePath);
  const binaryExtensions = ['.png', '.jpg', '.jpeg', '.gif', '.woff2', '.woff', '.ttf'];
  return binaryExtensions.includes(ext);
}

function walkDirectory(dir, basePath = '') {
  const files = {};

  const entries = fs.readdirSync(dir, { withFileTypes: true });

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    const relativePath = path.join(basePath, entry.name);

    if (entry.isDirectory()) {
      Object.assign(files, walkDirectory(fullPath, relativePath));
    } else if (entry.isFile()) {
      const content = fs.readFileSync(fullPath);
      const normalizedPath = relativePath.replace(/\\/g, '/');

      if (isBinaryFile(fullPath)) {
        files[normalizedPath] = {
          type: 'base64',
          contentType: getContentType(fullPath),
          content: content.toString('base64'),
        };
      } else {
        files[normalizedPath] = {
          type: 'utf8',
          contentType: getContentType(fullPath),
          content: content.toString('utf-8'),
        };
      }
    }
  }

  return files;
}

function main() {
  console.log('📦 Embedding static assets...');

  if (!fs.existsSync(PUBLIC_DIR)) {
    console.error(`❌ Public directory not found: ${PUBLIC_DIR}`);
    process.exit(1);
  }

  const assets = walkDirectory(PUBLIC_DIR);

  console.log(`   Found ${Object.keys(assets).length} files`);

  // Also embed shell tools if directory exists
  if (fs.existsSync(SHELL_DIR)) {
    console.log('📁 Embedding shell tools...');
    const shellFiles = walkDirectory(SHELL_DIR, 'shell');
    Object.assign(assets, shellFiles);
    console.log(`   Found ${Object.keys(shellFiles).length} shell files`);
  }

  const assetKeys = Object.keys(assets).sort();
  const totalSize = Object.values(assets).reduce((sum, asset) => {
    return sum + (asset.type === 'base64' ? Buffer.byteLength(asset.content, 'base64') : asset.content.length);
  }, 0);

  console.log(`   Total size: ${(totalSize / 1024).toFixed(1)} KB`);

  if (COMPRESS_ASSETS) {
    console.log('🗜️  Compressing text assets (HTML, CSS, JS)...');
    for (const key of Object.keys(assets)) {
      const asset = assets[key];
      if (asset.type === 'utf8' && (key.endsWith('.html') || key.endsWith('.css') || key.endsWith('.js') || key.endsWith('.mjs'))) {
        asset.compressed = true;
      }
    }
    console.log(`   Compressed ${Object.keys(assets).filter(k => assets[k].compressed).length} files`);
  }

  const output = `// Auto-generated by build-assets.mjs
// Do not edit this file manually

import { gunzipSync } from 'bun:zlib';

export const ASSETS = ${JSON.stringify(assets, null, 2)};

export function getAsset(path) {
  return ASSETS[path];
}

export function getAssetContent(path) {
  const asset = ASSETS[path];
  if (!asset) {
    return null;
  }
  if (asset.type === 'base64') {
    return Buffer.from(asset.content, 'base64');
  }
  if (asset.compressed) {
    // Decompress gzip content at runtime
    const compressed = Buffer.from(asset.content, 'base64');
    return gunzipSync(compressed).toString('utf-8');
  }
  return asset.content;
}

export function getAssetContentType(path) {
  const asset = ASSETS[path];
  if (ASSETS[path]?.compressed) {
    return 'application/gzip';
  }
  return ASSETS[path]?.contentType || 'application/octet-stream';
}
`;

  fs.mkdirSync(ASSETS_DIR, { recursive: true });
  fs.writeFileSync(OUTPUT_FILE, output);

  console.log(`✅ Generated: ${OUTPUT_FILE}`);
}

main();
